Correctly activate XPG4v2 support
To activate XPG4v2 (X/Open Portability Guide) support
_XOPEN_SOURCE_EXTENDED macro should have value 1. Just define this
macro is not enough.

I do not know who and why decide to play with _XOPEN_SOURCE macro, but
using it without number causes minimal XPG version usage and leads to
the following warning under OpenBSD:

xl2tpd.c:1017: warning: implicit declaration of function 'strcasecmp'

So fix _XOPEN_SOURCE_EXTENDED usage to activate minimal required XPG
version.